"""empty message

Revision ID: 0510e0ce73f9
Revises: a6a506eb40b9
Create Date: 2017-08-04 11:35:33.374756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0510e0ce73f9'
down_revision = 'a6a506eb40b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'chapter', ['chapter_id'], ['id'])
    op.drop_column('lesson', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('board_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###
