"""empty message

Revision ID: a6a506eb40b9
Revises: e05fed96acef
Create Date: 2017-08-03 17:12:48.038505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a506eb40b9'
down_revision = 'e05fed96acef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'title')
    # ### end Alembic commands ###
